defaults: &defaults
  docker:
    - image: cimg/node:18.13.0

version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    <<: *defaults
    steps:
      - node/install:
          node-version: v18.13.0
          install-yarn: true
      - checkout
      - run: yarn
      - run: yarn -s lint
      - run: yarn test
      - run: yarn typecheck

  publish:
    <<: *defaults
    steps:
      - node/install:
          node-version: v18.13.0
          install-yarn: true
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '86:3f:dd:d5:e0:f2:2a:a9:cd:46:67:2f:6c:68:27:68'
      - run: yarn
      - run:
          name: Build dist files
          command: yarn build
      - run:
          name: Publish to NPM with semantic-release
          command: CI=true nvm install 'lts/*' && npx semantic-release --debug

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - beta
